language: python
services:
  - docker
python:
  - "2.7"
# command to install dependencies
install:
  - make deps
# command to run tests
script:
  - make lint
  - make test

after_success:
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  api_key: ${HEROKU_API_KEY}
  app: protected-escarpment-37850
