language: python
services:
  - docker
python:
  - "2.7"
# command to install dependencies
install:
  - make deps
# command to run tests
lint:
  - make lint
script:
  - make test

after_success:
  - make docker_build
  - make docker_push
